"use client";

import cn from "clsx";
import { useRouter } from "next/navigation";
import { useEffect, useRef, useState } from "react";
import { SEARCH_PLACEHOLDER } from "lib/config/navigation";

type PagefindSubResult = { title: string; url: string; excerpt: string };
type PagefindResult = {
    url: string;
    excerpt: string;
    meta?: { title?: string };
    sub_results?: PagefindSubResult[];
};
type Pagefind = {
    options: (value: Record<string, unknown>) => Promise<void>;
    init: () => void;
    debouncedSearch: (
        query: string
    ) => Promise<{ results: { data: () => Promise<PagefindResult> }[] } | null>;
};

let pagefindPromise: Promise<Pagefind> | undefined;

async function getPagefind(): Promise<Pagefind> {
    pagefindPromise ??= (async () => {
        // The index only exists after `next build` + the `postbuild` pagefind
        // step, so the bundler must leave this import alone.
        const module = await import(
            /* webpackIgnore: true */ /* turbopackIgnore: true */
            // @ts-expect-error — the pagefind bundle only exists after `next build`.
            "/_pagefind/pagefind.js"
        );
        await module.options({ excerptLength: 20 });
        module.init();
        return module as Pagefind;
    })();
    return pagefindPromise;
}

/** Turns a pagefind index path back into a site route. */
function toRoute(url: string): string {
    return url.replace(/\.html$/, "").replace(/\/index$/, "") || "/";
}

export function SearchDialog({ className }: { className?: string }) {
    const router = useRouter();
    const inputRef = useRef<HTMLInputElement>(null);
    const containerRef = useRef<HTMLDivElement>(null);
    const [query, setQuery] = useState("");
    const [results, setResults] = useState<PagefindResult[]>([]);
    const [error, setError] = useState<string | null>(null);
    const [isOpen, setIsOpen] = useState(false);

    useEffect(() => {
        const onKeyDown = (event: KeyboardEvent) => {
            if (event.key === "k" && (event.metaKey || event.ctrlKey)) {
                event.preventDefault();
                inputRef.current?.focus();
            }
            if (event.key === "Escape") {
                setIsOpen(false);
                inputRef.current?.blur();
            }
        };
        document.addEventListener("keydown", onKeyDown);
        return () => document.removeEventListener("keydown", onKeyDown);
    }, []);

    useEffect(() => {
        if (!isOpen) return;
        const onPointerDown = (event: MouseEvent) => {
            if (!containerRef.current?.contains(event.target as Node)) {
                setIsOpen(false);
            }
        };
        document.addEventListener("mousedown", onPointerDown);
        return () => document.removeEventListener("mousedown", onPointerDown);
    }, [isOpen]);

    useEffect(() => {
        if (!query) {
            setResults([]);
            setError(null);
            return;
        }

        let cancelled = false;
        (async () => {
            try {
                const pagefind = await getPagefind();
                const search = await pagefind.debouncedSearch(query);
                if (cancelled || search === null) return;
                const data = await Promise.all(
                    search.results.slice(0, 10).map((result) => result.data())
                );
                if (!cancelled) {
                    setResults(data);
                    setError(null);
                }
            } catch {
                if (!cancelled) {
                    setResults([]);
                    setError(
                        "Search index unavailable — it is generated by `pnpm build`."
                    );
                }
            }
        })();

        return () => {
            cancelled = true;
        };
    }, [query]);

    const go = (url: string) => {
        setIsOpen(false);
        setQuery("");
        router.push(toRoute(url));
    };

    return (
        <div ref={containerRef} className={cn("relative", className)}>
            <input
                ref={inputRef}
                type="search"
                spellCheck={false}
                autoComplete="off"
                value={query}
                placeholder={SEARCH_PLACEHOLDER}
                aria-label="Search the Encyclopaedia"
                onChange={(event) => {
                    setQuery(event.target.value);
                    setIsOpen(true);
                }}
                onFocus={() => setIsOpen(true)}
                className={cn(
                    "docs-focus w-full rounded-lg px-3 py-1.5 text-sm transition-colors",
                    "bg-black/[.03] dark:bg-gray-50/10",
                    "text-gray-900 dark:text-gray-300",
                    "placeholder:text-gray-500 dark:placeholder:text-gray-400",
                    "md:w-64"
                )}
            />
            <kbd
                className={cn(
                    "pointer-events-none absolute end-1.5 top-1/2 -translate-y-1/2",
                    "rounded border border-gray-300 bg-white px-1.5 font-mono text-[10px] text-gray-500",
                    "dark:border-neutral-700 dark:bg-neutral-900 dark:text-gray-400",
                    "max-sm:hidden",
                    query && "hidden"
                )}
            >
                CTRL K
            </kbd>

            {isOpen && query && (
                <div
                    className={cn(
                        "docs-scrollbar absolute end-0 z-30 mt-2 max-h-[min(calc(100vh-5rem),400px)] w-full overflow-y-auto",
                        "rounded-md border border-black/5 py-2 text-sm shadow-lg dark:border-white/20",
                        "bg-white dark:bg-neutral-900",
                        "md:w-96"
                    )}
                >
                    {error && (
                        <p className="px-4 py-2 text-gray-500 dark:text-gray-400">
                            {error}
                        </p>
                    )}
                    {!error && results.length === 0 && (
                        <p className="px-4 py-2 text-gray-500 dark:text-gray-400">
                            No results for “{query}”.
                        </p>
                    )}
                    {results.map((result) => (
                        <div key={result.url} className="px-2 py-1">
                            <button
                                type="button"
                                onClick={() => go(result.url)}
                                className="block w-full cursor-pointer rounded px-2 py-1 text-start font-medium hover:bg-gray-100 dark:hover:bg-neutral-800"
                            >
                                {result.meta?.title ?? toRoute(result.url)}
                            </button>
                            {result.sub_results?.slice(0, 3).map((sub) => (
                                <button
                                    key={sub.url}
                                    type="button"
                                    onClick={() => go(sub.url)}
                                    className="block w-full cursor-pointer rounded px-2 py-1 text-start text-xs text-gray-600 hover:bg-gray-100 dark:text-gray-400 dark:hover:bg-neutral-800"
                                >
                                    <span className="font-medium">
                                        {sub.title}
                                    </span>
                                    <span
                                        className="ms-2 opacity-80"
                                        // biome-ignore lint/security/noDangerouslySetInnerHtml: <Pagefind excerpt markup from our own build>
                                        dangerouslySetInnerHTML={{
                                            __html: sub.excerpt,
                                        }}
                                    />
                                </button>
                            ))}
                        </div>
                    ))}
                </div>
            )}
        </div>
    );
}
