// AUTO-GENERATED by scripts/content/generate-meta-manifest.ts — do not edit.
// Regenerate whenever a content/**/_meta.{ts,tsx} file is added or removed.
import type { MetaModule } from "./types";
import meta_root from "content/_meta";
import meta_contributing from "content/contributing/_meta";
import meta_contributing_formatting from "content/contributing/formatting/_meta";
import meta_encyclopaedia_index from "content/encyclopaedia-index/_meta";
import meta_hegel from "content/hegel/_meta";
import meta_hegel_guides from "content/hegel/guides/_meta";
import meta_hegel_reference from "content/hegel/reference/_meta";
import meta_hegel_reference__annotations from "content/hegel/reference/_annotations/_meta";
import meta_hegel_reference__critiques from "content/hegel/reference/_critiques/_meta";
import meta_hegel_reference_becoming from "content/hegel/reference/becoming/_meta";
import meta_hegel_reference_being from "content/hegel/reference/being/_meta";
import meta_hegel_reference_constitution from "content/hegel/reference/constitution/_meta";
import meta_hegel_reference_determination from "content/hegel/reference/determination/_meta";
import meta_hegel_reference_existence from "content/hegel/reference/existence/_meta";
import meta_hegel_reference_limit from "content/hegel/reference/limit/_meta";
import meta_hegel_reference_mechanical_object from "content/hegel/reference/mechanical-object/_meta";
import meta_hegel_reference_mechanical_process from "content/hegel/reference/mechanical-process/_meta";
import meta_hegel_reference_mechanical_process_the_formal_mechanical_process from "content/hegel/reference/mechanical-process/the-formal-mechanical-process/_meta";
import meta_hegel_reference_nothing from "content/hegel/reference/nothing/_meta";
import meta_hegel_reference_quality from "content/hegel/reference/quality/_meta";
import meta_hegel_reference_something from "content/hegel/reference/something/_meta";
import meta_hegel_reference_something_and_other from "content/hegel/reference/something-and-other/_meta";
import meta_kant from "content/kant/_meta";
import meta_kant_guides from "content/kant/guides/_meta";
import meta_kant_reference from "content/kant/reference/_meta";
import meta_spinoza from "content/spinoza/_meta";
import meta_spinoza_guides from "content/spinoza/guides/_meta";
import meta_spinoza_reference from "content/spinoza/reference/_meta";

/** Keyed by directory path relative to `content/` ("" is the content root). */
export const metaModules: Record<string, MetaModule> = {
    "": meta_root,
    "contributing": meta_contributing,
    "contributing/formatting": meta_contributing_formatting,
    "encyclopaedia-index": meta_encyclopaedia_index,
    "hegel": meta_hegel,
    "hegel/guides": meta_hegel_guides,
    "hegel/reference": meta_hegel_reference,
    "hegel/reference/_annotations": meta_hegel_reference__annotations,
    "hegel/reference/_critiques": meta_hegel_reference__critiques,
    "hegel/reference/becoming": meta_hegel_reference_becoming,
    "hegel/reference/being": meta_hegel_reference_being,
    "hegel/reference/constitution": meta_hegel_reference_constitution,
    "hegel/reference/determination": meta_hegel_reference_determination,
    "hegel/reference/existence": meta_hegel_reference_existence,
    "hegel/reference/limit": meta_hegel_reference_limit,
    "hegel/reference/mechanical-object": meta_hegel_reference_mechanical_object,
    "hegel/reference/mechanical-process": meta_hegel_reference_mechanical_process,
    "hegel/reference/mechanical-process/the-formal-mechanical-process": meta_hegel_reference_mechanical_process_the_formal_mechanical_process,
    "hegel/reference/nothing": meta_hegel_reference_nothing,
    "hegel/reference/quality": meta_hegel_reference_quality,
    "hegel/reference/something": meta_hegel_reference_something,
    "hegel/reference/something-and-other": meta_hegel_reference_something_and_other,
    "kant": meta_kant,
    "kant/guides": meta_kant_guides,
    "kant/reference": meta_kant_reference,
    "spinoza": meta_spinoza,
    "spinoza/guides": meta_spinoza_guides,
    "spinoza/reference": meta_spinoza_reference,
};
