onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - core-js
  - esbuild
  - prisma
  - protobufjs
  - sharp

overrides:
  '@babel/plugin-transform-modules-systemjs@>=7.12.0 <=7.29.3': '>=7.29.4'
  '@protobufjs/utf8@<=1.1.0': '>=1.1.1'
  '@tootallnate/once@<3.0.1': '>=3.0.1'
  cookie@<0.7.0: '>=0.7.0'
  diff@>=5.0.0 <5.2.2: '>=5.2.2'
  effect@<3.20.0: '>=3.20.0'
  fast-uri@<=3.1.0: '>=3.1.1'
  fast-uri@<=3.1.1: '>=3.1.2'
  fast-xml-builder@<=1.1.6: '>=1.1.7'
  fast-xml-builder@=1.1.5: '>=1.1.6'
  js-yaml@>=4.0.0 <4.1.1: '>=4.1.1'
  lodash-es@>=4.0.0 <=4.17.22: '>=4.17.23'
  mermaid@>=11.0.0-alpha.1 <=11.14.0: '>=11.15.0'
  next@>=10.0.0 <16.1.7: '>=16.1.7'
  next@>=15.6.0-canary.0 <16.1.5: '>=16.1.5'
  next@>=16.0.0 <16.2.5: '>=16.2.5'
  next@>=16.0.0 <16.2.6: '>=16.2.6'
  next@>=16.0.0-beta.0 <16.0.11: '>=16.0.11'
  next@>=16.0.0-beta.0 <16.1.5: '>=16.1.5'
  next@>=16.0.0-beta.0 <16.1.7: '>=16.1.7'
  next@>=16.0.0-beta.0 <16.2.3: '>=16.2.3'
  next@>=16.0.1 <16.1.7: '>=16.1.7'
  postcss@<8.5.10: '>=8.5.10'
  preact@>=10.28.0 <10.28.2: '>=10.28.2'
  protobufjs@<=7.5.5: '>=7.5.6'
  uuid@<14.0.0: '>=14.0.0'
