/**
 * Emits `lib/content/meta.generated.ts`: static imports of every
 * `content/**\/_meta.{ts,tsx}` module, keyed by directory.
 *
 * The `_meta` files contain TS and JSX, so they have to be imported as
 * modules rather than read from disk — and dynamic `import()` with a computed
 * path is not statically analysable by the bundler. Hence the manifest.
 *
 * Run via `predev`/`prebuild`; the output is committed.
 *
 *   bun run scripts/content/generate-meta-manifest.ts
 */
import fs from "node:fs";
import path from "node:path";

const ROOT = process.cwd();
const CONTENT_DIR = path.join(ROOT, "content");
const OUTPUT = path.join(ROOT, "lib/content/meta.generated.ts");

type MetaFile = { dir: string; importPath: string };

function collect(dir: string, out: MetaFile[]) {
    for (const entry of fs
        .readdirSync(dir, { withFileTypes: true })
        .sort((a, b) => a.name.localeCompare(b.name))) {
        const full = path.join(dir, entry.name);
        if (entry.isDirectory()) {
            collect(full, out);
        } else if (entry.name === "_meta.ts" || entry.name === "_meta.tsx") {
            const relativeDir = path
                .relative(CONTENT_DIR, dir)
                .split(path.sep)
                .join("/");
            out.push({
                dir: relativeDir,
                importPath: `content${relativeDir ? `/${relativeDir}` : ""}/_meta`,
            });
        }
    }
}

const metaFiles: MetaFile[] = [];
collect(CONTENT_DIR, metaFiles);
metaFiles.sort((a, b) => a.dir.localeCompare(b.dir));

const identifier = (dir: string) =>
    `meta_${dir === "" ? "root" : dir.replace(/[^a-zA-Z0-9]/g, "_")}`;

const contents = `// AUTO-GENERATED by scripts/content/generate-meta-manifest.ts — do not edit.
// Regenerate whenever a content/**/_meta.{ts,tsx} file is added or removed.
import type { MetaModule } from "./types";
${metaFiles.map((file) => `import ${identifier(file.dir)} from "${file.importPath}";`).join("\n")}

/** Keyed by directory path relative to \`content/\` ("" is the content root). */
export const metaModules: Record<string, MetaModule> = {
${metaFiles.map((file) => `    ${JSON.stringify(file.dir)}: ${identifier(file.dir)},`).join("\n")}
};
`;

fs.writeFileSync(OUTPUT, contents);
console.info(
    `Wrote ${metaFiles.length} _meta imports to ${path.relative(ROOT, OUTPUT)}`
);
